sudo: required
services: 
    - docker
before_install:
    - chmod 0755 ./client/node_modules/.bin/jest
    - chmod +x ./client/node_modules/.bin/react-scripts
    - docker build -t atparte1/react-test -f ./client/Dockerfile.dev ./client
script:
    - docker run -e CI=true atparte1/react-test npm run test -- --coverage
after_success:
    - docker build -t atparte1/multi-client ./client
    - docker build -t atparte1/multi-nginx ./nginx
    - docker build -t atparte1/multi-server ./server
    - docker build -t atparte1/multi-worker ./worker
#LOG IN TO DOCKER cli
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
# take images and push them to docker hub
    - docker push atparte1/multi-client
    - docker push atparte1/multi-nginx
    - docker push atparte1/multi-server
    - docker push atparte1/multi-worker
deploy:
    edge: true
    provider: elasticbeanstalk
    region: "us-east-1"
    app: "muti-docker"
    env: "MutiDocker-env"
    bucker_name: elasticbeanstalk-us-east-1-746694212378
    bucket_path: muti-docker
    on: 
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: 
        secure: $AWS_SECRET_KEY
