apiVersion: skaffold/v1beta2
kind: Config
build:
    local:
        push: false
    artifacts:
        -   image: atparte1/multi-client
            context: client
            docker: 
                dockerfile: Dockerfile.dev
            sync:
                '**/*.js': .
                '**/*.css': .
                '**/*.html': .
