apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metadata:
    name: letsencrypt-prod
spec:
    acme:
        server: https://acme-v02.api.letsencrypt.org/directory
        e-mail: 'a2lparte@gmail.com'
        privateKeySecretRef:
            name: letsencrypt-prod
        solvers:
            - http01:
                ingress:
                    class: nginx
